spring.application.name=phishing-prototype

spring.datasource.url=jdbc:postgresql://localhost:5432/thesis
spring.datasource.username=thesis
spring.datasource.password=thesis

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.thymeleaf.cache=false